default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: db

development:
  <<: *default
  database: rkj_development

test:
  <<: *default
  database: rkj_test

production:
  <<: *default
  database: rkj_production
  username: root
  password: <%= Rails.application.credentials.send(Rails.env.to_s)[:db_passwd] %>
  host: kds-mydb.cqzwdxy4ocr4.ap-northeast-1.rds.amazonaws.com
